# Generated by Django 2.0.6 on 2019-05-23 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('T_name', models.CharField(max_length=20)),
                ('pwd', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=5)),
            ],
        ),
    ]
