# Generated by Django 2.0.6 on 2019-05-23 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin01', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='emplist',
            table='emplist',
        ),
    ]
