# Generated by Django 2.0.6 on 2019-05-27 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin01', '0002_auto_20190523_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='emplist',
            name='headpic',
            field=models.ImageField(default=111, upload_to='pic'),
            preserve_default=False,
        ),
    ]
